id: P010360
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:45:52.877533
source_metadata:
  id: bdr:W1KG12629
  title: རྡོ་རྗེ་ཕུར་པའི་རབ་གནས་བྱིན་རླབས་འདོད་དགུའི་ཆར།
  author: ''
  volumes:
    4efcb639edda4206b1699d0bdc579602:
      image_group_id: I1KG12645
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
